### ISSUE TITLE
[Feature] Update Usage documentation for new custom dir within the hypr dir

### ISSUE THREAD

**Issue by yrnmsk** [end-4/dots-hyprland-wiki#8]
## Issue
Current documentation for Configuring Hyprland under Usage is stale.

Changes to the conf files within the hyprland dir should not be recommended anymore after the introduction of the new `custom` dir in [4c0cc1](https://github.com/end-4/dots-hyprland/commit/4c0cc1237afb49c5802fefb46be3b81f3b3550d6).

## Feature
Update the documentation so that it reflects the new method of applying user customization by introducing the `custom` dir layered atop end-4's defaults. User customizations within that custom dir are now preserved even after syncing and updating via the installation script.

**Comment by clsty** [comment]
Welp, I'm just about to work on it. Thanks for the reminder anyway.

**Comment by clsty** [comment]
When editing this part:

> For the statusbar, edit `~/.config/ags/modules/bar/system.js`. Change `"%H:%M"` according to the format described [here](https://docs.gtk.org/glib/method.DateTime.format.html).

@end-4 Could you please make this one configurable via `user_options.js` too?
- Also please allow custom interval because user may prefer a 1000 ms interval for using `%H:%M:%S` format.
- It will be even better if the date format could also be configurable.

Thanks in advance.
